### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by melodiemonod** [MLGlobalHealth/phyloSI-RakaiAgeGender#9]
Need to update https://github.com/MLGlobalHealth/phyloSI-RakaiAgeGender/blob/main/src/confidential_data_pipeline/README.md with the new data location on Zonodo. 

Shozen do you think you could do it please? Let me know if you don't have access to the Zonodo folder!

**Comment by ShozenD** [comment]
Hi @melodiemonod. No problem! I have access to the repository so I will fix the necessary paths!

**Comment by ShozenD** [comment]
@abriz97 @melodiemonod Sorry, I might need help with this one after all. I have access to the Zenodo folder, but I can't see the confidential data directory (if it exists).

**Comment by abriz97** [comment]
Hi both, 
I can help, so please feel free to provide more detail. FYI:
- No confidential data should be put on Zenodo (these are data to share). 
- There is no single "confidential data" directory, these are stored in different locations on the HPC.
You can specify your mountpoint to the deepdata and deepseq directory in the config.R script, so that we people at Imperial have an easy way to access these files, while outsiders won't be able to load them.
Let me know if this helps
